### PR TITLE
Adding an interactive quiz on ironman movies for viewer interaction✨

### PR DESCRIPTION
**Pull request by shriyadindi**
I've Added an interactive quiz on ironman movies for viewer interaction.
issue no. : #342 

https://github.com/user-attachments/assets/d11ca6b7-7ce6-4cf7-b1dc-ea5b465e55dc

### CODE REVIEW

**Comment by shriyadindi** [comment]
@aslams2020 If you liked it, Kindly assign a level 3 label for this

**Comment by shriyadindi** [comment]
@aslams2020 Okay I'll update the changes

**Comment by shriyadindi** [comment]
@aslams2020 Made the changes..
https://github.com/aslams2020/Stark-Tech-Portfolio/pull/356

**Comment by aslams2020** [comment]
Okay @shriyadindi , Will close this one then.
thanks

**Pull request closed without merging**
