### PR TITLE
Feedback section added.

### PR DESCRIPTION
**Pull request by Codewithmeowmeow**
i have added the feedback section and also attached the video.
kindly review it and assign it as level 2 atleast:)

https://github.com/user-attachments/assets/8009078d-db05-4104-aa6e-78b96bad286b

#202

### CODE REVIEW

**Comment by aslams2020** [comment]
@Codewithmeowmeow Can u make the feedback form as i told you in @202 ? 
making a separate feedback form page would be better ig.

**Comment by aslams2020** [comment]
Like this - (this was my work when i used to be a contributor)

image

**Comment by Codewithmeowmeow** [comment]
Hey that was great...i will do mt best.

**Comment by aslams2020** [comment]
yeah @Codewithmeowmeow. make sure to link it in the footer 
and follow the website's colour theme

**Pull request closed without merging**
