### PR TITLE
style.css file updated, issue number #404 is solved

### PR DESCRIPTION
**Pull request by Hemraj-7**
style.css file updated, issue number #404  is solved.

this code does not affect previous code ( website ).

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Footer's responsiveness has been affected 

Original - 
image


After your changes - 
image

**Comment by Hemraj-7** [comment]
> Footer's responsiveness has been affected
> 
> Original - image
> 
> After your changes - image

Okay, I'm checking

**Comment by Hemraj-7** [comment]
know updated 

Screenshot 2024-11-09 174557

**Comment by MastanSayyad** [comment]
@Hemraj-7 Admin is active, wait for him

**Review by aslams2020 — APPROVED** [review]

**Pull request merged**
