### PR TITLE
Added a Villain Page

### LINKED ISSUE #250: Add a Villain Page
I want to add a Villain page that will feature the villains that Iron Man fought in the MCU universe and comics(since you have that on your site). I will provide a timeline for both, mentioning the most prominent villains(the comics have many villains).

I would like to work on the issue. I will update you about the work progress and share with you to know your feedback along the way. I would request your cooperation and feedback.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved

- Closes #250 

# Description
1. Added the new Marvel Villains page: 
I have added a **Villain page** featuring the MCU villain's timeline that Iron Man fought in the MCU universe and comics.

2. Redirect to the **Marvel Villains** page from every page footer
I have added redirects to the Villains Page by replacing the **Media Kit** in the footer section

# Screenshots/Videos

1. Added the new Marvel Villains page: 

https://github.com/user-attachments/assets/56b5ddba-7259-49a1-bf7c-04e5dca54c12

2. Redirect to the **Marvel Villains** page from every page footer

- Before
image

- After
image

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@aslams2020 Please review the PR at your convenience. I would appreciate a **level3** label if you feel so and might be possible at your end.

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Great Work @rajdeepchakraborty-rc 

I think the images are not loading properly, can you check it - 
image

**Comment by rajdeepchakraborty-rc** [comment]
@aslams2020 Sure. Please give me 15-20 mins. I will have dinner and then check it and let you know.

**Comment by aslams2020** [comment]
Sure. Take your time

**Comment by rajdeepchakraborty-rc** [comment]
> Sure. Take your time

@aslams2020 I pulled the updated changes from the main branch. The Blog page has recently been added, I have modified the Villain page Navbar and also added a redirect in the Footer section of the Blog page.

Also about the image render issue, I checked it and it is working fine on my end. Please check again at your end and let me know.

**Comment by aslams2020** [comment]
@rajdeepchakraborty-rc Okay, at my end it is not displaying the images. 

Will merge it for now and let's see.. If the images are still displayed, will you resolve it in another additional PR?

**Review by aslams2020 — APPROVED** [review]
Great Job @rajdeepchakraborty-rc ! I appreciate the changes

**Comment by rajdeepchakraborty-rc** [comment]
Also after I pulled the updated changes from your main branch, I noticed something:
image
Someone might be working on some issue and has opened a similar folder as mine. It was different because the contributor misspelled **Villains**. This might cause confusion. If you want I can change my folder name to Marvel_Villains

**Comment by aslams2020** [comment]
@rajdeepchakraborty-rc in the deployed website, the images are not displayed. Will you fix it in an additional PR (that PR i can't give level)

**Comment by rajdeepchakraborty-rc** [comment]
> Also after I pulled the updated changes from your main branch, I noticed something: image Someone might be working on some issue and has opened a similar folder as mine. It was different because the contributor misspelled **Villains**. This might cause confusion. If you want I can change my folder name to Marvel_Villains

@aslams2020 Do you want to keep the folder name like this?

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc in the deployed website, the images are not displayed. Will you fix it in an additional PR (that PR i can't give level)

Yes, you don't have to. This is related to this issue I will check it.

**Comment by aslams2020** [comment]
@rajdeepchakraborty-rc About that folder name, you can update it your folder name to - `Marvel_Villains` 
So it'll not create confusion.

Thanks for noticing!

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc About that folder name, you can update it your folder name to - `Marvel_Villains` So it'll not create confusion.
> 
> The other folder name -- let that be as it is..
> 
> Thanks for noticing!

Ok. Also sorry for the inconvenience caused by this PR. I am not sure what went wrong on the deployment side. I will check and try to resolve the issue.

**Comment by aslams2020** [comment]
Yeah, it's fine. You can fix it anytime -- if you've other pending works you can prioritize them if you want to.

**Comment by rajdeepchakraborty-rc** [comment]
> Yeah, it's fine. You can fix it anytime -- if you've other pending works you can prioritize them if you want to.

@aslams2020 It's fine. I want to resolve this issue first. As of now, I don't have any assigned pending issues. I will try resolving this issue first.

Also If I open a PR I will link my issue to that PR:

- Issue #250

**Pull request merged**
