### PR TITLE
video and movies updated

### PR DESCRIPTION
**Pull request by t1nt1n-s0lv3r**
@aslams2020 I have successfully updated the movies and watch videos pages in your website 

edit: Please  can you help with this conflict
image

### CODE REVIEW

**Review by aslams2020 — APPROVED** [review]
Approved #8

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Great Work @t1nt1n-s0lv3r, Can You make both the Pages Responsive and make hamburger work? 


https://github.com/user-attachments/assets/30bbf461-e43d-4569-bdde-b697d125d945



Will reward level3 for that.

**Comment by t1nt1n-s0lv3r** [comment]
ok sure

**Comment by aslams2020** [comment]
> bro i am actually having exams so i wont be able to do it properly can you push mine for now

Okay

**Comment by aslams2020** [comment]
Hi, @t1nt1n-s0lv3r 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
