### PR TITLE
Changes in the alignment of the content when screen is made smaller

### PR DESCRIPTION
**Pull request by Sneha22072005**
I have made the changes. They are all in media query.

Issue #4

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Great work. 
Can you please reduce the size of search bar in media query - 

image

make these changes and commit again. (no need to make new PR.)

**Comment by Sneha22072005** [comment]
I have made the changes as required.

**Review by aslams2020 — APPROVED** [review]
@Sneha22072005 Great work! You made it responsive

**Comment by Sneha22072005** [comment]
I resolved the conflicts and committed the changes too

**Review by aslams2020 — APPROVED** [review]
Approved. (Also please give before and after results next time, for better comparing the changes)

**Pull request merged**
