### PR TITLE
Added Blogs Page | Issue #255

### LINKED ISSUE #255: Implementation of Blog Page
I want to implement the Blog Page.

https://github.com/user-attachments/assets/b0f05a88-ce1e-4cdf-974e-c092f12950c2

### PR DESCRIPTION
**Pull request by Shariq2003**
fix #255 

I have added the Blogs Page that contain the Blogs,

Eg.

1. Title: The Evolution of Iron Man: From Comic to Cinematic Icon

- Description: Explore the journey of Tony Stark from his comic book origins to becoming a beloved superhero in the Marvel Cinematic Universe. Discover how Robert Downey Jr.'s portrayal revolutionized superhero films and set the stage for the entire MCU.

2. Title: Women of Marvel: Breaking Barriers in the MCU

- Description: A look at the strong female characters in the Marvel Cinematic Universe, from Black Widow to Captain Marvel. This blog post highlights their impact on the franchise and how they inspire audiences worldwide.

3. Title: The Infinity Saga: A Retrospective on the MCU's Biggest Arcs

- Description: Dive into the Infinity Saga and revisit the pivotal moments that shaped the Marvel Cinematic Universe. This post covers key films, character arcs, and the interconnected storylines that kept fans on the edge of their seats.

4. Title: The Future of the MCU: What’s Next for Marvel?

- Description: Speculations and insights into upcoming Marvel films and TV series. Explore fan theories and the potential direction of the Marvel Cinematic Universe post-Endgame.
 and more.............................
   

https://github.com/user-attachments/assets/fe541128-0420-44fa-bae2-81d9aa559422

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
The images are not matching with the blog title..
Also the layout, design and everything is the same as "Comics" page. It should be different as these are blogs page.

**Add 6 blogs** 

Please add relevant images to the blogs according to their title, you can refer similar below example 
image

**Comment by Shariq2003** [comment]
> The images are not matching with the blog title.. Also the layout, design and everything is the same as "Comics" page. It should be different as these are blogs page.
> 
> **Add 6 blogs**
> 
> Please add relevant images to the blogs according to their title, you can refer similar below example image

okay

**Comment by aslams2020** [comment]
@Shariq2003 Any updates ?

**Comment by Shariq2003** [comment]
@aslams2020 sir, will raise the PR by tonight

**Review by aslams2020 — COMMENTED** [review]
PLease make a new PR @Shariq2003

**Comment by Shariq2003** [comment]
> PLease make a new PR @Shariq2003

okay @aslams2020 sir

**Comment by aslams2020** [comment]
Yeah Sure.

**Comment by Shariq2003** [comment]
> Yeah Sure.

Thanks alot sir

**Comment by Shariq2003** [comment]
@aslams2020 sir, Now I have added the 6 Blogs referred from this website [LINK](https://marvelcinematicuniverse.fandom.com/wiki/Blog:Recent_posts)
Also, make the page look like a Blogs Page with the theme conservation of the website.



https://github.com/user-attachments/assets/8c5f76e2-d264-4a1c-a0f6-157aa0eaee05

**Comment by Shariq2003** [comment]
@aslams2020 sir, Please review this PR on priority because if you merge any other PR, than this PR will face conflict in the files, as I have also change the navbar for navigation to this page, in multiple pages.

**Review by aslams2020 — APPROVED** [review]
Approved

**Comment by Shariq2003** [comment]
@aslams2020 sir, but new page should be of level 3
Am right ?

**Comment by aslams2020** [comment]
Hi @Shariq2003,
Creating a new Page does not actually guarentee a level3. As it is not dependant on number of lines.

i reviewed - 
- In the Blogs page, The navbar and footer are integrated from the homepage (as it should be)
- The layout of the cards and the styling of them is not newly styled as it is similar to `movies` and `comics` pages. Which make no difference in creating a different kind of development idea.
- Also the page is not responsive

I hope you understand, Why i gave level2 for it.

happy coding!

**Comment by Shariq2003** [comment]
> Hi @Shariq2003, Creating a new Page does not actually guarentee a level3. As it is not dependant on number of lines.
> 
> i reviewed -
> 
> * In the Blogs page, The navbar and footer are integrated from the homepage (as it should be)
> * The layout of the cards and the styling of them is not newly styled as it is similar to `movies` and `comics` pages. Which make no difference in creating a different kind of development idea.
> * Also the page is not responsive
> 
> I hope you understand, Why i gave level2 for it.
> 
> happy coding!

Okay what if I make it responsive in my new PR on which you don't have  to add any level, just make this PR to level 3.

**Comment by aslams2020** [comment]
I can give that PR Level1.

As this PR will be a even then, because of the 2nd point. As it is crucial to showcase our developer ideas in whatever work we do.

If you wish to make it responsive, please create an issue first.

**Comment by Shariq2003** [comment]
> I can give that issue's PR Level1.
> 
> As this current PR will be a even then a level2, because of the 2nd point. As it is crucial to showcase our developer ideas in whatever work we do.
> 
> If you wish to make it responsive, please create an issue first.

Yes sir, I just take the same styling to match the theme of the website, nothing else.

**Pull request merged**
