### PR TITLE
Improving Overflow of Images over navbar

### PR DESCRIPTION
**Pull request by VidhanThakur09**
Change the orientation of the navbar to avoid overflow of images over the bar

Issue number #27

### CODE REVIEW

**Review by aslams2020 — APPROVED** [review]

**Comment by aslams2020** [comment]
Good work!

**Comment by aslams2020** [comment]
Congrats On your First Contribution🚀

**Comment by VidhanThakur09** [comment]
Thank you 😊

**Comment by aslams2020** [comment]
Hi, @VidhanThakur09 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Comment by VidhanThakur09** [comment]
Please accept my sincere congratulations on your recovery. I truly appreciate your unwavering support and diligent efforts.

**Pull request merged**
