### PR TITLE
Updated the readme file 

### PR DESCRIPTION
**Pull request by Aman-G-upta**
Done with the changes Updated the readme file 
fixes:#238 
Merge it please @aslams2020

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
image
Instead of above image, can you add the new hactoberfest logo, as mentioned in the issue

**Comment by Aman-G-upta** [comment]
Added images as mentioned in issue

**Comment by aslams2020** [comment]
Sorry for the oversight.
image
Could you please add this instead of above?

**Comment by aslams2020** [comment]
image

**Review by aslams2020 — APPROVED** [review]
Thanks @Aman-G-upta

**Pull request merged**
