### PR TITLE
Update contact page

### PR DESCRIPTION
**Pull request by Abdus-8747**
First of all sorry as my original branch got some issues so have to delete it

Although I have made all changes which were suggested
Screenshot (23)

### CODE REVIEW

**Comment by aslams2020** [comment]
Hi, Please note that, I'll be able to review and merge the PR Tomorrow. Not today because of travelling.

**Comment by Abdus-8747** [comment]
@aslams2020 Thankyou for letting me know,

I hope that you review and merge it as early as possible.

**Review by aslams2020 — APPROVED** [review]
Approved #237

**Review by aslams2020 — APPROVED** [review]
Thankyou for being patient.
keep contributing🚀

**Comment by Abdus-8747** [comment]
Thank you so much @aslams2020 for guiding me properly to work on the project.

And so it was my first contribution it was an amazing experience working with you.

**Pull request merged**
