### PR TITLE
Enhanced scroll back button with timeline on it for smoother functioning.

### PR DESCRIPTION
**Pull request by shriyadindi**
Enhanced scroll back button with timeline on it for smoother functioning.
issue no. : #357 
I've added the enhanced version of the scroll back button with progress ring for every page, and have set the theme according to the website.

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Can u please make it red? 

like this: 
image

**Comment by shriyadindi** [comment]
@aslams2020 I tried red first, but it looks too bland so I went with golden to match with the iron man suit.

**Comment by aslams2020** [comment]
> @aslams2020 I tried red first, but it looks too bland so I went with golden to match with the iron man suit.

Fine, Let it be then

**Review by aslams2020 — APPROVED** [review]
Approved

**Pull request merged**
