### PR TITLE
Villain Page Timeline Image Render

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Related Issue

- Issue #250 

# Description

1. In the previous PR #367, the Villain images were not rendered. Tried to resolve it in this PR.
2. Renamed the Folder structure I used from `Villains` to `Marvel_Villains` to remove ambiguity in existing `Villans` Folder

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@aslams2020 Please check the deployment and let me know if the issue is resolved.

**Review by aslams2020 — APPROVED** [review]
Approved!

**Comment by aslams2020** [comment]
@rajdeepchakraborty-rc Great work!

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Great work!

@aslams2020 Thanks a lot! I was looking forward to this contribution, being an Iron Man fan myself. The issue really caused a disturbance in my mind after you informed me about the rendering problem. I wanted to resolve it as soon as possible. I am glad it is working fine now.

Thanks for reviewing the PR and hope you have a great day/night ahead!

**Pull request merged**
