### PR TITLE
Adding Navbar and Footer for the quiz page and making it responsive. (Issue #359)

### PR DESCRIPTION
**Pull request by shriyadindi**
Adding Navbar and Footer for the quiz page and making it responsive. 
Issue no.:  #359

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Why is there the code for Scroll-to-top button in every page? 

i just merged the other PR for it #360

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Also, the font style of the footer is not same as the homepage footer.
image

**Comment by shriyadindi** [comment]
@aslams2020 I'll Make a new PR for it.

**Comment by aslams2020** [comment]
okay

**Pull request closed without merging**
