### PR TITLE
Add Pre-loader

### PR DESCRIPTION
**Pull request by soumyajit254**
I add Pre-loader.

### CODE REVIEW

**Comment by aslams2020** [comment]
Nice work @soumyajit254 
Can we replace it with something different than the logo in header(as it is small too..)
image

You can add something like this : 
image


OR if you have any other idea, feel free to tell me.

**Comment by soumyajit254** [comment]
I update this, and now the logo is big

**Comment by aslams2020** [comment]
It is good. But can we replace that logo with any other animated gifs ?

**Comment by aslams2020** [comment]
@soumyajit254 Hi, My Account got recovered, You can start working on the Issue. 
Sorry for the inconvience. Keep Contributing 🚀

**Comment by Peart-Guy** [comment]
@aslams2020 
I want to add a customized animated preloader to you webapp which will match the theme and aesthetic of the site.

This is a basic sample to showcase what I can offer. The final product may vary depending on your specific needs and preferences. I look forward to the opportunity to contribute to your project .

https://github.com/user-attachments/assets/e5db73da-2e6b-4639-b8c1-8c74d21c75e8

**Comment by aslams2020** [comment]
Hi @Peart-Guy Thankyou for your intrest to work on the project. 
#180 i.e, @soumyajit254 is **already assigned** to this task of adding a preloader. If he not able to do the work in next coming days. Will assign you

thank you. you can still find and raise new issues.

**Comment by Peart-Guy** [comment]
@aslams2020  
Kindly assign me this issue I will add it within tomorrow

**Comment by aslams2020** [comment]
@soumyajit254 Thankyou for the work. But due to no Response to the requested changes, i have to close this PR and assign to @Peart-Guy

**Pull request closed without merging**
