### PR TITLE
footer responsiveness

### PR DESCRIPTION
**Pull request by Dhavisco**
Kindly review the changes. Thank you
#305 
image

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Great job! Also, Can we center that logo?

**Comment by Dhavisco** [comment]
Fixed in the new commit 
image

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Hi, actually you did really a great job! 
but the original footer in desktop has been completely changed.

original - 
image

After your changes -
image

can you please only change the media queries and dont make changes to existing footer code, replace it as it was earlier. (you can take help of this PR code review of what you deleted.)

**Comment by Dhavisco** [comment]
I have restored the footer and made the required changes. Sorry if I made changes to the initial footer (desktop). It has been restored and edited on media query
Kindly review my last commit. Thank you.

Also, note that I raised an issue to fix the hero session responsiveness of the page.

image


image

**Review by aslams2020 — APPROVED** [review]
Good work @Dhavisco !

**Comment by Dhavisco** [comment]
Thank you. Weldone
Happy Hacktoberfest.

Hope I am not late to the party 😄

**Pull request merged**
