### PR TITLE
Added Social media-icons in footer

### LINKED ISSUE #36: ADD a Social media -Icon in footer section
Hello @aslams2020 , there is missing social media icons like facebook, twitter,etc.

please assign this issue to me :)

### PR DESCRIPTION
**Pull request by Pooja3Bhattrai**
closes #36 
Resolved issue:  Added social media -icons in footer with a very nice hover -effect.

### CODE REVIEW

**Comment by Pooja3Bhattrai** [comment]
Please merge under 
socail icon
GSSOC EXTD and HACKTOBERFEST24  accepted .
Thank you !

**Review by aslams2020 — APPROVED** [review]
Please reduce the size of icons and Font size too.
and shift it here - 
image

**Comment by aslams2020** [comment]
Also, Resolve the conflicts

**Comment by Pooja3Bhattrai** [comment]
> Please reduce the size of icons and Font size too. and shift it here

also reduce font-size of "follow us on"??

**Comment by aslams2020** [comment]
Yes

**Comment by Pooja3Bhattrai** [comment]
is it perfect or need change to be made?

copyy

**Comment by aslams2020** [comment]
Yeah, It;s ok. Commit the changes.

**Comment by aslams2020** [comment]
@Pooja3Bhattrai Please commit the changes you made

**Comment by Pooja3Bhattrai** [comment]
yes, i have made the changes. you may merge pull request.

**Review by aslams2020 — CHANGES_REQUESTED** [review]
I see that there's an issue in the  homepage. 
Also i saw that you updated the code of Navbar. Please fix it as it was earlier and make changes only to the footer and those logos

image

**Comment by Pooja3Bhattrai** [comment]
thankyou for noticing ...it is done, i have updated  can you pls check from your side,??? is it fine??

**Review by aslams2020 — APPROVED** [review]
Approved!

**Comment by aslams2020** [comment]
Hi, @Pooja3Bhattrai 

I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
