### PR TITLE
Added the variant section and made required changes issue#62

### PR DESCRIPTION
**Pull request by swethapadmavathimukku**

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Original website Homepage -

https://github.com/user-attachments/assets/39324d2e-57a3-46c6-b6c9-140291528d32


After changes - 

https://github.com/user-attachments/assets/532681f0-d58c-45c2-8afa-1cb4a60ae12e


The variants page is looking good. but please make sure the homepage is unaffected.

**Comment by swethapadmavathimukku** [comment]
okay, I will do my best in solving it

**Comment by aslams2020** [comment]
Yeah, 
in index.html - just add the link to variant.html where i told you
and link the variants page there.

Please make sure not to delete the css code of other, i reviewed the code changes and found that you removed some existing css

**Comment by swethapadmavathimukku** [comment]
I am sorry, I am just new to this competiton

**Comment by aslams2020** [comment]
> I am sorry, I am just new to this competiton

@swethapadmavathimukku It is ok. That is why i am guiding you. 
Atleast you are trying.

**Comment by aslams2020** [comment]
You can still Ask if any doubts regarding my instructions to get clarity.

**Comment by swethapadmavathimukku** [comment]
Okay  thank you , so after the changes do I have to pull a new pull request

**Comment by aslams2020** [comment]
> Okay thank you , so after the changes do I have to pull a new pull request

So, Whenever you are assigned to an issue, make sure you **"pull the changes" in your forked clone.** (so that your branch will have the updated code) 

If you not pull the changes then it will create conflicts which may break the UI of website (hence we cant merge it)

Hence, I suggest you to first pull the changes in your branch, then make the required changes in that branch. then make the pull request (that is how we do things..)

**Comment by swethapadmavathimukku** [comment]
okay thankyou

**Pull request closed without merging**
