### PR TITLE
Back to Top button

### PR DESCRIPTION
**Pull request by saadgibawa**
I have added a "Back to Top" button for improved navigation. I am attaching a video demonstrating the functionality of the button.

https://github.com/user-attachments/assets/24a68411-c7d6-49d3-ac69-2ffee2e0b94f

Please review the changes, and let me know if any further adjustments are needed!

### CODE REVIEW

**Comment by aslams2020** [comment]
Great Work @saadgibawa!
Can we add a small fade in animation to it? so that it will appear smoothly.? 


https://github.com/user-attachments/assets/a6bae087-fbbb-438b-8415-73b609997bbf

**Comment by aslams2020** [comment]
Ping me when it's done.

**Comment by saadgibawa** [comment]
@aslams2020 sure

**Comment by saadgibawa** [comment]
@aslams2020 added the fade effect 
Please review the changes and let me know if any further adjustments are needed

https://github.com/user-attachments/assets/d88a8732-1b9a-4b73-aef3-a45d079ebcd7

**Review by aslams2020 — APPROVED** [review]
Approved!

**Comment by aslams2020** [comment]
Hi, @saadgibawa 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
