### PR TITLE
Redesigned the hero section 

### PR DESCRIPTION
**Pull request by swatified**
Hey this is how it looks like. I tried to keep the shadows and styles as same so that it goes with the rest website. I just worked on index.html and style.css. That too on first section as you said. Kindly check out the video and assign me the level as you think it is worth of : 

https://github.com/user-attachments/assets/bf69360c-e89e-4be2-8be1-49da493a8109

### CODE REVIEW

**Comment by swatified** [comment]
@aslams2020 This is regarding my issue #147 under gssoc-ext and hacktoberfest, kindly link and add required tags before merging. Thank you.

**Review by aslams2020 — APPROVED** [review]
Approved

**Comment by aslams2020** [comment]
Hi, @swatified 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Comment by swatified** [comment]
@aslams2020 thank you for the tag! I was quite anxious about this 🥲

**Pull request merged**
