### PR TITLE
a_index.html added

### PR DESCRIPTION
**Pull request by anjali5Xcode**
#307

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
it is not working properly...It should not take other type entries.
image

**Comment by aslams2020** [comment]
It is not poping up. 

also i wanted to say that --  the phone number field should not take any string alphabets as input

**Comment by anjali5Xcode** [comment]
i have made changes in a_index.html file

**Comment by anjali5Xcode** [comment]
Please Review the changes in a_index.html file

**Comment by anjali5Xcode** [comment]
which file you are viewing a_index.html that i have created or index.html because i had made changes in a_index.html file 
although i have make changes in index.html also 
now, please check it again

**Comment by aslams2020** [comment]
But why a_index.html file? 

Now it is working fine but still a_index.html will create confusion in future can we remove that file without affecting the current original index.html?

**Comment by aslams2020** [comment]
I resolved the conflicts. please remove the extra file `a_index.html`

**Comment by anjali5Xcode** [comment]
I have done like this till now.
I apologize for the inconvenience. 
Now i have removed the a_index.html file.
please check it

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Now it looks like this. I think some code is overlapped. 
Please check it, sorry for the continous "Requested Changes" But it is necessary so that Website functions properly after merging.


https://github.com/user-attachments/assets/32524d67-512b-452b-aae4-0ae47d429846



let me know when it is done.

**Review by aslams2020 — APPROVED** [review]
Approved

**Pull request merged**
