### PR TITLE
 add the variant section and I made the required changes issue#62

### PR DESCRIPTION
**Pull request by swethapadmavathimukku**

### CODE REVIEW

**Comment by aslams2020** [comment]
@swethapadmavathimukku See after trying you did it! Good work

**Comment by swethapadmavathimukku** [comment]
Thank you so much, It could not be done without guidance.

And could you please add the labels to this

**Review by aslams2020 — APPROVED** [review]
Approved #62

**Comment by aslams2020** [comment]
Make sure to remember these things. It'll help you throughout the open source contributions.

**Comment by swethapadmavathimukku** [comment]
yeah surely, Thank you so much for helping me in my first contribution

**Comment by aslams2020** [comment]
Hi, @swethapadmavathimukku 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
