### PR TITLE
adding back to top button

### PR DESCRIPTION
**Pull request by saadgibawa**
added the button

### CODE REVIEW

**Comment by saadgibawa** [comment]
closes #140

**Comment by aslams2020** [comment]
@saadgibawa Great work.

**Review by aslams2020 — APPROVED** [review]
Approved.

**Comment by saadgibawa** [comment]
@aslams2020 Thankyou for the opportunity. It was a wonderful experience contributing to your project!

**Comment by aslams2020** [comment]
Keep Contributing🚀

**Pull request merged**
