### PR TITLE
Added a Preloader

### PR DESCRIPTION
**Pull request by Peart-Guy**
I have added the Custom Preloader
Closes : #229 
@aslams2020 Kindly check it out

https://github.com/user-attachments/assets/2b798049-05f2-4d6c-a408-157cc0b1246e

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Good work, can u make the below changes - 
1. Currently The preloader comes with the navbar above it, **it should come before** any element in website loads. 
When the preloader is there, the background website of it should not be visible
image

2. Please reduce the size of the arc reactor, as it can affect eye with the flash.

**Comment by aslams2020** [comment]
Let me know, if u have any doubts.

**Comment by Peart-Guy** [comment]
@aslams2020  
I have made the necessary changes. Kindly Check it out

**Review by aslams2020 — APPROVED** [review]
Great Work @Peart-Guy

**Comment by Peart-Guy** [comment]
> Great Work @Peart-Guy

Thanks

**Pull request merged**
