### PR TITLE
changes by tanishraj7

### PR DESCRIPTION
**Pull request by tanishraj7**
done for GSSoC 24

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Cant see any significant changes in the button - 

original -
image

after changes - 
image


It would be good if u can customize them to look different and more attractive.

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Also please dont add ur name in the codebase. please update it to more meaningful btn name.

image

**Comment by tanishraj7** [comment]
okay

**Comment by tanishraj7** [comment]
did both the changes 
made the first 3 buttons more attractive 
Screenshot 2024-10-30 194315
and also changed the class name for variant button
Screenshot 2024-10-30 194339

**Pull request merged**
