### PR TITLE
appearances page logo size fix

### PR DESCRIPTION
**Pull request by vedant3337**
closes issue #199 

before:

image

after:

image

### CODE REVIEW

**Comment by vedant3337** [comment]
@aslams2020 

**please review and close this pr asap with labels.**

**Comment by aslams2020** [comment]
Hi, Please note that, I'll be able to review and merge the PR Tomorrow. Not today because of travelling.

**Comment by vedant3337** [comment]
@aslams2020 

**please review and close this pr asap with labels.**

**Review by aslams2020 — COMMENTED** [review]
It seems that the issue has already been resolved. Please don't make use of "Format Document" just to increase the number of lines.
It is difficult to review the code changes. And it should not be done. hope you understand.

image

**Comment by aslams2020** [comment]
Merging The PR, because of inactiveness of my github due to github policies,This issue may have been resolved by someone else. 
Or else, you could have done that.

**Pull request merged**
