### PR TITLE
Change in CSS in class firsthalf,secondhalf-img and added secondhalf:hover

### PR DESCRIPTION
**Pull request by AyutheCoder**
As you required the smooth floating of left side content and Ironman image,I had the changes, please have a look over it and please accept the changes.

https://github.com/user-attachments/assets/6db2aa6f-0a6f-4b37-bf9d-a8244babe1e3

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Make the time duration for both text nd image same.

**Comment by aslams2020** [comment]
Also next time please avoid doing "Format document" while in vs code, it'll just increase the number of lines changed.
As u can see it created confict in the entire index.html file

**Comment by aslams2020** [comment]
For now, I am resolving the conflicts. please make the required changes then i'll merge.
It's ok it happens. But please remember this as a contributor :)

**Comment by aslams2020** [comment]
@AyutheCoder Can u please make a new PR without changing the index.html ? 
As i can after resolving conflicts the index.html code is changed completely.

Please do changes in the css only for animations.

**Comment by AyutheCoder** [comment]
Sir,I had made the time duration same

**Comment by AyutheCoder** [comment]
Should I create a new pull request?

**Comment by aslams2020** [comment]
@AyutheCoder Great work. 
Yes please create a new pull request and make changes in only css file.

**Comment by AyutheCoder** [comment]
Ok Sir

**Comment by AyutheCoder** [comment]
Sir,I had removed the index.html file as I hadn't made any changes to it

**Comment by aslams2020** [comment]
@AyutheCoder Don't delete the index.html as it will be deleted from my side too after merge.
Do this - 
- Copy the css code changes u made from here.
- Create a new branch and make changes in that
- Create pull request.

**Comment by AyutheCoder** [comment]
I had changed only css file,firsthalf,secondhalf img,and added secondhalf:hover,please  check is it okay now and accept the changes

**Comment by aslams2020** [comment]
> Sir,I had removed the index.html file as I hadn't made any changes to it

Actually, removing index.html results in deletion of original too.

**Comment by aslams2020** [comment]
Ask me if any doubt.

**Comment by AyutheCoder** [comment]
Ok sir,I'm creating it,

**Pull request closed without merging**
