### PR TITLE
Added back to top button

### PR DESCRIPTION
**Pull request by saadgibawa**
Added the button across all the pages. Issue no. #140 
Please review the changes, and let me know if any further adjustments are needed!

### CODE REVIEW

**Comment by aslams2020** [comment]
Can u resolve the Conflicts

**Comment by aslams2020** [comment]
@saadgibawa If Are u having Difficulties with resolving the conflicts.
 I would suggest you to Make a new PR so that it will be easy for you too

**Comment by aslams2020** [comment]
As i can see That u have tried many times resolving the conflicts.

**Comment by saadgibawa** [comment]
Okay. Thanks! 
should i close this one?

**Comment by aslams2020** [comment]
Yeah, make a new PR so that it'll be easy for u

**Pull request closed without merging**
