### PR TITLE
Fixed #55 : Automated Greeting Workflow

### LINKED ISSUE #55: FEATURE: Automated Greeting Workflow
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @aslams2020  please assign me this task with label "gssoc-ext" and "level1"

### PR DESCRIPTION
**Pull request by samyak-aditya**
Fixed #55 

**Description:**
This pull request implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.

**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
  - **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

**Implementation Details:**
- Created a workflow file named `greetings.yml` in the `.github/workflows` directory.
- Configured the workflow to trigger on both new issues and pull requests.
- Utilized the `actions/first-interaction` action to manage the greeting messages.

This enhancement aims to foster a welcoming environment for contributors and improve community engagement.

### CODE REVIEW

**Review by aslams2020 — APPROVED** [review]
Approved. Let's see how it works

**Comment by aslams2020** [comment]
It is not working. I tested by creating an issue. 
Can u check? Otherwise i will have to revert it

**Comment by samyak-aditya** [comment]
Let me check

**Comment by aslams2020** [comment]
It worked👍

**Comment by samyak-aditya** [comment]
I checked it Its working

SSHOT

**Comment by aslams2020** [comment]
Hi, @samyak-aditya 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
