### PR TITLE
added the variants section  issue #62

### PR DESCRIPTION
**Pull request by swethapadmavathimukku**

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Can u please make a new PR with your proposed changes?
I think **you didn't Pulled the new changes** in the repo to your branch as i said at the time i assigned you. (Our current website is Different now, due to new updates)

https://github.com/user-attachments/assets/a59a09b3-ab45-4bdb-8cd7-13297b694363

Also Please write the correct path - 
image

**Comment by swethapadmavathimukku** [comment]
okay

**Comment by aslams2020** [comment]
@swethapadmavathimukku I really liked the page you made, I would suggest you to make a new branch and make changes like this in that (You can copy the code you submitted here in this PR, I will not close it till you make new one) 

NOTE : Please add the link to Variants.html page here - 
image

**Comment by aslams2020** [comment]
If doubts. You can ask

**Comment by swethapadmavathimukku** [comment]
okay

**Pull request closed without merging**
