### PR TITLE
Created Privacy Policy and Terms of Service Pages and Added Links to Footer

### PR DESCRIPTION
**Pull request by VidhanThakur09**
Fixed issue #232 
# Description

## This pull request adds two new pages to the website:

- **Privacy Policy**: Outlines how we collect, use, and protect user data.
- **Terms of Service**: Specifies the terms and conditions governing the use of the website.

Links to these pages have been added to the footer section of the website for easy access.

### New Pages:

- `PrivacyPolicy.html`
- `Terms&Conditions.html`
- The pages are styled with custom styling `term.css` to match the overall website theme and is optimized for readability on various devices. 

### Footer Links:

- Updated the landing page footer to include links to the new pages.

## Testing:

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

## Video

https://github.com/user-attachments/assets/ecb5daa0-9be2-4d44-b450-a386e825b55a

### CODE REVIEW

**Comment by aslams2020** [comment]
Hi @VidhanThakur09 
I'll not be able to review it today, I'm in travelling. 
Will review and merge tomorrow! Sorry for the inconvenience.

**Comment by VidhanThakur09** [comment]
It's  fine ,wish you a safe and wonderful journey.

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Hi @VidhanThakur09 Can you make both the heading color #f7b011 ?
and change the font style of both page headings More better? 

Giving level3, coz both pages are responsive as well.

**Comment by aslams2020** [comment]
let me know when you are done.

**Comment by VidhanThakur09** [comment]
Screenshot 2024-10-28 174953


@aslams2020 how about now

**Review by aslams2020 — APPROVED** [review]
Approved! @VidhanThakur09 good work.

**Comment by VidhanThakur09** [comment]
> Approved! @VidhanThakur09 good work.

Thank you for your insightful and valuable feedback.

**Pull request merged**
