### PR TITLE
Updated the search bar styling. 

### PR DESCRIPTION
**Pull request by hannah-maria**
- Added a red border to match the theme of the page
- Added a search icon which zooms in slightly on hover

Screenshot 2024-10-02 at 3 41 18 PM

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Please **decrease the size of search bar**, as it is too big maybe by decreasing padding. 
shift **search bar to the right corner.** 
**Change the colour of the input field** when we type something in it to differentiate

**Original Navbar** 
image


**After Changes -** 
image

**Comment by aslams2020** [comment]
@hannah-maria

**Comment by hannah-maria** [comment]
@aslams2020 alright! will change the size of the bar. The input text was made white bc black was hard to read, you want me to change it from white?

**Comment by aslams2020** [comment]
> @aslams2020 Alright! will change the size of the bar. The input text was made white bc black was hard to read, you want me to change it from white?

No, I am talking about the input field colour. Not input text(it's better as white)

image

you can give **white border** to the search bar.

**Comment by aslams2020** [comment]
@hannah-maria

**Pull request closed without merging**
