### PR TITLE
Fixed Logo Responsiveness | #109

### PR DESCRIPTION
**Pull request by SurajSG23**
Hey, I just fixed your logo's responsiveness, 

Issue number: #109 

as you can see in the old styling the logo's size was not properly structured,

Screenshot 2024-10-05 205405

i fixed it and added some cool breathing glow effect to enhance the UI of your website, check it out!!

https://github.com/user-attachments/assets/5ab1e1b2-9927-4563-a2b9-b7a80ec1ca70

Hope you liked it! 🙏 Please label me gssoc and hacktober fest and a level label too.
THANK YOU..

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Great work @SurajSG23. 
Can you please reduce the size of the glow effect on the logo and also decrease it's opacity.(keep it less, like negligible) so that it will not cause distraction.

https://github.com/user-attachments/assets/7fc07cbf-9a57-4a6b-ab5b-5e2f8e378f3c

**Comment by SurajSG23** [comment]
Hey, i have made changes take a look !


https://github.com/user-attachments/assets/1d520250-0221-4029-ac08-2f2d1ae07024

Now the shadow effect doesn't happen too frequently and with low opacity.
And the responsiveness is also fixed! 
Hope you like it.Thank You

**Review by aslams2020 — APPROVED** [review]
Approved!

**Comment by aslams2020** [comment]
Hi, @SurajSG23 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
