### PR TITLE
 feat: add a contributers page . #241 

### PR DESCRIPTION
**Pull request by AE-Hertz**
feat: add a contributers page . #241 

Closes: #241 

accept this under hacktoberfest and gssoc-ext, i am expecting level 3 label, thank you.

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Please link the page correctly in the footer I am not able to review it.
Also, **Please Move the .css file in the css folder.** 
image
image

**Comment by aslams2020** [comment]
@AE-Hertz

**Comment by AE-Hertz** [comment]
@aslams2020 ok. Can you confirm its happening with footer links. Right?

**Comment by aslams2020** [comment]
Yeah, in footer..as given in screenshot above

**Comment by aslams2020** [comment]
Hi, Please note that, I'll be able to review and merge the PR Tomorrow. Not today because of travelling.

**Comment by AE-Hertz** [comment]
@aslams2020 okay thats fine, i resolved the issues. but please make sure to add labels before merge in Pr and issue. safe travels...

**Comment by AE-Hertz** [comment]
@aslams2020 and one more thing, do you need a "in development page" for pages which are still under development? let me know so i will raise issue.

**Comment by AE-Hertz** [comment]
@aslams2020 hoping my PR gets merged.

**Comment by AE-Hertz** [comment]
Also if you can upgrade the level that would be great. Thank you

**Review by aslams2020 — CHANGES_REQUESTED** [review]
1. Why "Become Associate" button linked to Some 'Kv-Nexus' repo? 
image

2.  Please remove that repo link and replace that button with "Our Repository" and add a link of this repo there.
image

3. Change the main heading in Above image as 'Stark Tech Contributors'.

**Comment by aslams2020** [comment]
@AE-Hertz Please make the requested changes, will merge the PR after that.
thankyou for being patient.

**Comment by AE-Hertz** [comment]
@aslams2020 i have changed the requested changes and also changed the "become associate" -> "become contributor" button, if you want i can rollback to "become associate".

**Review by aslams2020 — APPROVED** [review]
Approved! Good work @AE-Hertz

**Comment by AE-Hertz** [comment]
@aslams2020 thank you.

**Pull request merged**
