### PR TITLE
Bug fixed #132 

### LINKED ISSUE #132: [BUG] in contact page, in the section of "Enter your name " there are some bug which may include digits in name
#### There is a bug on the contact page in the "Enter your name" section that allows users to input digits into the name field. This issue can lead to confusion, as names typically do not contain numbers. To fix this, input validation should be implemented to restrict the field to alphabetic characters only. Additionally, providing users with clear instructions on acceptable input can enhance user experience and ensure that names are entered correctly.

image

### PR DESCRIPTION
**Pull request by anish013326**
## i have fix bug which i have created earlier #132 

image

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Good work! Can you please add the Labels to input field? as i told you in the issue comment. 

Also please remove the counter arrows from the phone no. input field.

image

**Comment by anish013326** [comment]
#### i have add input lable and also remove counter arrow plz check it and merge it.

image

**Review by aslams2020 — APPROVED** [review]
Approved.

**Comment by aslams2020** [comment]
Hi, @anish013326  
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Pull request merged**
