### PR TITLE
Add footer which is crucial for navigation.

### PR DESCRIPTION
**Pull request by akshattiwarii**
Issue #81 
- Before;
before

- After:
after

### Reason of adding this feature
1. Navigation and User Experience.
2. Contact Information.
3. Branding and Trust.
4. Search Engine Optimization. (SEO)
5. Design Balance.

If it helps you to boost the website productivity so please give gssoc selected tag.

### CODE REVIEW

**Comment by akshattiwarii** [comment]
https://github.com/user-attachments/assets/7217869d-a5f0-4a1b-b8f6-b8448addb808

**Comment by akshattiwarii** [comment]
Video Attached:
https://www.veed.io/view/af58f2e5-6c90-4e1c-a6cc-2c37c87a33a3?panel=share

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Can we Shift that Line Inside the footer you made? As that last black space will be removed.

image

**Comment by aslams2020** [comment]
@akshattiwarii Please make the requested changes. Then we'll merge it.
Good work

**Comment by akshattiwarii** [comment]
ohk wait I am doing changes

**Review by akshattiwarii — COMMENTED** [review]
Changes done in footer section.

**Review by aslams2020 — APPROVED** [review]
Good work @akshattiwarii

**Comment by akshattiwarii** [comment]
Thank you sir.

**Pull request merged**
