### PR TITLE
add vote poll system in movies page

### LINKED ISSUE #419: add voting system
adding an option that lets user vote for their fav movie outta the given movies in movie page

### PR DESCRIPTION
**Pull request by Riyachauhan11**
fixes #419 

added a vote poll system in movies page that lets user vote for their fav movie from all the given movies in page.
A user can only vote once for their fav movie and the current top most voted movie will be displayed in the voting box.

changes made:

https://github.com/user-attachments/assets/a43bb58c-f884-4bee-9ff3-72cebcd381e3

### CODE REVIEW

**Comment by Riyachauhan11** [comment]
@BrindaManani pls review it

**Review by aslams2020 — APPROVED** [review]

**Review by BrindaManani — APPROVED** [review]
Looks great.

@aslams2020  It's done from my side, Please check it.

**Comment by aslams2020** [comment]
@BrindaManani Yeah! good work

**Comment by BrindaManani** [comment]
@aslams2020 Thank you

**Pull request merged**
