### PR TITLE
Added Comics Section In The Navbar, Including all the Popular comics

### PR DESCRIPTION
**Pull request by AyutheCoder**
1.)Added Comics.html -In this I had used the same background as present in other sections and added the images of different comics with short description and with clickable links which direct to comics on clicking on images.
2.)Added comic section link in index.html,appearance.html,movies.html,video.html.
3.)Added imdd-rating in CSS.
4.)Added functionality in JS for comic section

https://github.com/user-attachments/assets/0c572b38-02e9-41c6-ac54-e7961ae0ea78

### CODE REVIEW

**Comment by AyutheCoder** [comment]
@aslams2020 Sir,I had added the comic section,please review and accept the changes.

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Hey @AyutheCoder Good work.
Can u please make the following changes - 
1. This white stripe is there, **can u remove it?**
image

2. Please make **Text Correction -**  
image

3. Please **Interchange these both links** in the navbar 
image

**Comment by aslams2020** [comment]
If you'd like to add a favicon to that page. You can

**Comment by AyutheCoder** [comment]
OK sir,I will make the changes

**Comment by AyutheCoder** [comment]
Sir,I had made the changes,kindly check.
I-1
I-2

**Review by aslams2020 — APPROVED** [review]
Approved. 
Also Can you please mention the issue no. you were assigned to? whenever making a PR

**Comment by aslams2020** [comment]
#111

**Comment by AyutheCoder** [comment]
Issue Number- #111

**Comment by AyutheCoder** [comment]
Thank you Sir

**Comment by aslams2020** [comment]
Hi, @AyutheCoder 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀

**Comment by AyutheCoder** [comment]
OK Sir

**Pull request merged**
