### PR TITLE
Add hover effects in nav and footer

### PR DESCRIPTION
**Pull request by shaina123786**
Fixed issue #209 

Add hover effects in nav and enhance footer .

### CODE REVIEW

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Good work. some changes are required - 
1. **In Navbar :** On Hovering the Navlinks, It is scaling up but **it affects the position of other links**, please keep others as it is and alsso **reduce the scaling size.**

https://github.com/user-attachments/assets/e6b11091-4d33-4f62-bc28-42f98b42bc60

2. Please **remove the yellow text shadow in navlinks** on hover

3. **In footer :** On hovering here also **other links are affected by scaling up**, fix it
4. On hovering the Social icons, it is disturbing the copyright statement of footer.

https://github.com/user-attachments/assets/d59bb7e3-eddb-4987-ba28-02ef7113b315

**Comment by aslams2020** [comment]
Let me know, when you are done.

**Comment by shaina123786** [comment]
Ok

**Comment by shaina123786** [comment]
I've addressed all the issues you raised:

Navbar: Reduced the scaling effect on hover for nav links and ensured it no longer affects the position of other links. Also removed the yellow text shadow on hover.
Footer: Fixed the scaling on hover for footer links so it doesn’t affect other links.
Social Icons: Resolved the issue where hovering over social icons disturbed the copyright statement.
plz review it and accept my PRs.

**Review by aslams2020 — APPROVED** [review]
Good work @shaina123786

**Pull request merged**
